spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://oci:3306/stylelab?autoReconnect=true&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: coby
    password: Tjdska0302!

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: debug