name: cd
on:
  push:
    branches: [ develop ]

jobs:
  ci-test: 
    runs-on: ubuntu-latest 
    steps: 
    - name: check out git repository
      uses: actions/checkout@v4  

    - name: dir list
      run: ls -al
      
    - name: Set up JDK 11 
      uses: actions/setup-java@v4
      with:
        java-version: 11 
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Test with Gradle
      run: ./gradlew test
      
    ## create application-dev.yml
    - name: make application-dev.yml
      run: |
        # create application-dev.yml
        cd ./src/main/resources

        # application-dev.yml 파일 생성
        touch ./application-dev.yml

        # GitHub-Actions 에서 설정한 값을 application-dev.yml 파일에 쓰기
        echo "${{ secrets.APPLICATION_DEV_YAML }}" | base64 --decode > src/main/resources/application-dev.yml
      shell: bash

    - name: is application-dev.yml
      run: ls src/main/resources
